"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowDownUp, ArrowRight, Bookmark, Building2, CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardList, Copy, Database, Download, LayoutList, LockKeyhole, MapPin, Moon, RefreshCw, Search, Settings2, SlidersHorizontal, Sparkles, Sun, X } from "lucide-react";
import { api, downloadFile } from "../lib/client";
import { ageLabel, makeCsv, money, permitActivityDate, permitDate, priorityLabel } from "../lib/permit-utils";
import { COUNTIES, DEFAULT_FILTERS, TRADES, type AgeFilter, type Assessment, type Filters, type LeadState, type Permit, type PermitPage, type Profile, type WorkspaceData } from "../lib/types";
import PermitDetail from "./permit-detail";
import Settings from "./settings";
import Sources from "./sources";
import { Brand, Dialog, EmptyState, Spinner, Toast, type ToastMessage } from "./ui";

type Tab = "permits" | "saved" | "sources" | "settings";
const AGE_ITEMS: { key: AgeFilter; label: string; stat?: "total" | "today" | "yesterday" | "twoDays" | "week" | "older" }[] = [{ key: "all", label: "All permits", stat: "total" }, { key: "today", label: "Today", stat: "today" }, { key: "yesterday", label: "Yesterday", stat: "yesterday" }, { key: "two-days", label: "2 days ago", stat: "twoDays" }, { key: "week", label: "Last 7 days", stat: "week" }, { key: "older", label: "Older permits", stat: "older" }];
const TABS = [{ key: "permits" as Tab, label: "Permits", icon: ClipboardList }, { key: "saved" as Tab, label: "Saved leads", icon: Bookmark }, { key: "sources" as Tab, label: "Sources", icon: Database }, { key: "settings" as Tab, label: "Settings", icon: Settings2 }];
const newLead: LeadState = { status: "new", notes: "" };

export default function Dashboard({ theme, toggleTheme, onLocked }: { theme: string; toggleTheme: () => void; onLocked: () => void }) {
  const [tab, setTab] = useState<Tab>("permits"), [data, setData] = useState<WorkspaceData | null>(null), [bootError, setBootError] = useState("");
  const [filters, setFilters] = useState<Filters>(DEFAULT_FILTERS), [search, setSearch] = useState(""), [page, setPage] = useState(1), [pageSize, setPageSize] = useState(10), [result, setResult] = useState<PermitPage | null>(null), [loading, setLoading] = useState(true), [loadError, setLoadError] = useState("");
  const [version, setVersion] = useState(0), [selected, setSelected] = useState<Set<string>>(new Set()), [detail, setDetail] = useState<Permit | null>(null), [toast, setToast] = useState<ToastMessage | null>(null), [filterOpen, setFilterOpen] = useState(false), [filterDraft, setFilterDraft] = useState(DEFAULT_FILTERS), [exporting, setExporting] = useState(false), [saving, setSaving] = useState(false), [accountOpen, setAccountOpen] = useState(false), [locking, setLocking] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null), accountRef = useRef<HTMLDivElement>(null);
  const notify = useCallback((message: string, error = false) => setToast({ message, error, id: Date.now() }), []);
  const closeToast = useCallback(() => setToast(null), []);
  const navigate = useCallback((next: Tab) => { setTab(next); setDetail(null); setSelected(new Set()); setPage(1); setLoadError(""); setFilters(current => ({ ...current, leadStatus: "all" })); window.history.replaceState(null, "", `#${next}`); }, []);
  const boot = useCallback(async () => {
    setBootError("");
    try { const payload = await api<WorkspaceData>("/api/workspace"); setData(payload); setFilters(current => ({ ...current, propertyType: payload.profile.commercialOnly ? "Commercial" : "all" })); }
    catch (e) { setBootError(e instanceof Error ? e.message : "Please try again."); }
  }, []);
  useEffect(() => { boot(); const initial = window.location.hash.slice(1); if (TABS.some(item => item.key === initial)) setTab(initial as Tab); }, [boot]);
  useEffect(() => { const timer = setTimeout(() => { setFilters(current => current.q === search ? current : { ...current, q: search }); setPage(1); }, 220); return () => clearTimeout(timer); }, [search]);
  useEffect(() => {
    function key(event: KeyboardEvent) { const target = event.target as HTMLElement; if (event.key === "/" && !["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName) && !target.isContentEditable && (tab === "permits" || tab === "saved")) { event.preventDefault(); searchRef.current?.focus(); } }
    function click(event: MouseEvent) { if (!accountRef.current?.contains(event.target as Node)) setAccountOpen(false); }
    window.addEventListener("keydown", key); document.addEventListener("click", click); return () => { window.removeEventListener("keydown", key); document.removeEventListener("click", click); };
  }, [tab]);
  const queryString = new URLSearchParams({ ...Object.fromEntries(Object.entries(filters).map(([key, value]) => [key, String(value)])), page: String(page), pageSize: String(pageSize), view: tab === "saved" ? "saved" : "permits" }).toString();
  useEffect(() => {
    if (!data || (tab !== "permits" && tab !== "saved")) return;
    const controller = new AbortController(); setLoading(true); setLoadError("");
    api<PermitPage>(`/api/permits?${queryString}`, { signal: controller.signal }).then(payload => { setResult(payload); if (payload.total && page > Math.ceil(payload.total / pageSize)) setPage(Math.ceil(payload.total / pageSize)); }).catch(e => { if (e?.name !== "AbortError") setLoadError(e instanceof Error ? e.message : "Please try again."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [queryString, data, tab, version, page, pageSize]);
  useEffect(() => { if (!data?.backendConnected) return; const timer = setInterval(() => { if (document.visibilityState === "visible") setVersion(value => value + 1); }, 1200000); return () => clearInterval(timer); }, [data?.backendConnected]);

  function changeFilters(update: Partial<Filters>) { setFilters(current => ({ ...current, ...update })); setPage(1); setSelected(new Set()); }
  function resetFilters() { setSearch(""); setFilters({ ...DEFAULT_FILTERS, propertyType: data?.profile.commercialOnly ? "Commercial" : "all" }); setPage(1); setSelected(new Set()); }
  async function copy(text: string, label: string) { try { await navigator.clipboard.writeText(text); notify(`${label} copied.`); } catch { notify("Copy isn't available in this browser. Select the text to copy it.", true); } }
  async function updateLeads(updates: { id: string; status?: LeadState["status"]; notes?: string }[], message = "Lead updated.") {
    try { const payload = await api<{ leads: Record<string, LeadState> }>("/api/leads", { method: "POST", body: JSON.stringify({ updates }) }); setData(current => current ? { ...current, leads: payload.leads } : current); setVersion(value => value + 1); notify(message); }
    catch (e) { notify(e instanceof Error ? e.message : "Please try again.", true); throw e; }
  }
  async function saveProfile(profile: Profile) {
    try { const payload = await api<{ profile: Profile }>("/api/profile", { method: "POST", body: JSON.stringify(profile) }); setData(current => current ? { ...current, profile: payload.profile } : current); setFilters(current => ({ ...current, propertyType: profile.commercialOnly ? "Commercial" : "all" })); setVersion(value => value + 1); notify("Your preferences are saved."); }
    catch (e) { notify(e instanceof Error ? e.message : "Please try again.", true); throw e; }
  }
  async function bookmark(permit: Permit) {
    const state = data?.leads[permit.id]?.status || "new";
    if (state === "contacted" || state === "won") { setDetail(permit); return; }
    try { await updateLeads([{ id: permit.id, status: state === "saved" ? "new" : "saved" }], state === "saved" ? "Lead removed from saved." : "Lead saved to your shortlist."); } catch {}
  }
  async function bulkSave() { if (!data) return; setSaving(true); try { await updateLeads(Array.from(selected).map(id => ({ id, status: ["new", "dismissed"].includes(data.leads[id]?.status || "new") ? "saved" : data.leads[id].status })), `${selected.size} leads saved.`); setSelected(new Set()); } catch {} finally { setSaving(false); } }
  async function assess(ids: string[]) {
    try { const payload = await api<{ assessments: Record<string, Assessment> }>("/api/jev/assess", { method: "POST", body: JSON.stringify({ ids }) }); if (detail && payload.assessments[detail.id]) setDetail({ ...detail, assessment: payload.assessments[detail.id], priority: payload.assessments[detail.id].score }); setVersion(value => value + 1); notify("Jev assessment complete."); }
    catch (e) { notify(e instanceof Error ? e.message : "Please try again.", true); throw e; }
  }
  async function exportCsv() {
    if (!data || !result) return; setExporting(true);
    try { let blob: Blob; let exportMessage = "Your filtered permits were exported."; if (selected.size) blob = new Blob([makeCsv(result.permits.filter(p => selected.has(p.id)), data.leads)], { type: "text/csv;charset=utf-8" }); else { const response = await fetch(`/api/export?${queryString}`, { credentials: "same-origin", cache: "no-store" }); if (!response.ok) { const payload = await response.json() as { error?: string }; if (response.status === 401) onLocked(); throw new Error(payload.error || "Export failed."); } blob = await response.blob(); const exported = Number(response.headers.get("X-Exported-Rows")), matching = Number(response.headers.get("X-Total-Matching")); if (matching > exported) exportMessage = `Exported ${exported.toLocaleString()} of ${matching.toLocaleString()} matching permits. Narrow your filters to export the remaining records.`; }
      downloadFile(blob, `permitline-permits-${new Date().toISOString().slice(0, 10)}.csv`); notify(selected.size ? `${selected.size} selected permits exported.` : exportMessage);
    } catch (e) { notify(e instanceof Error ? e.message : "Please try again.", true); } finally { setExporting(false); }
  }
  async function lock() { setLocking(true); try { await api("/api/auth/logout", { method: "POST", body: "{}" }); onLocked(); } catch (e) { notify(e instanceof Error ? e.message : "Please try again.", true); } finally { setLocking(false); } }

  const savedCount = data ? Object.values(data.leads).filter(lead => ["saved", "contacted", "won"].includes(lead.status)).length : 0;
  const rows = result?.permits || [], stats = result?.stats, totalPages = Math.max(1, Math.ceil((result?.total || 0) / pageSize)), allSelected = rows.length > 0 && rows.every(row => selected.has(row.id));
  const hasFilters = filters.q || filters.county !== "all" || filters.trade !== "all" || filters.status !== "all" || filters.minimumValue > 0 || filters.onlyServiceArea || !filters.hideDismissed || filters.age !== "all";
  const ageTitle = filters.age === "today" ? "Today's permits." : filters.age === "yesterday" ? "Yesterday's permits." : filters.age === "two-days" ? "Permits from 2 days ago." : filters.age === "week" ? "This week's permits." : filters.age === "older" ? "Older permits." : "Find your next project.";

  return <div className="dashboard-shell"><header className="app-header"><button className="brand-button" aria-label="Go to permits" onClick={() => navigate("permits")}><Brand/></button><nav className="top-nav" aria-label="Main navigation">{TABS.map(({ key, label, icon: Icon }) => <button className={tab === key ? "active" : ""} key={key} onClick={() => navigate(key)} aria-current={tab === key ? "page" : undefined}><Icon size={17}/><span>{label}</span>{key === "saved" && savedCount > 0 && <span className="nav-count">{savedCount}</span>}</button>)}</nav><div className="header-actions"><span className="workspace-mode"><span className="status-dot"/>{data?.backendConnected ? "Connected workspace" : "Feed unavailable"}</span><button className="icon-button" onClick={toggleTheme} aria-label={theme === "dark" ? "Use light theme" : "Use black theme"}>{theme === "dark" ? <Sun size={19}/> : <Moon size={19}/>}</button><div className="account-menu" ref={accountRef}><button className="avatar-button" aria-label="Workspace account menu" aria-expanded={accountOpen} onClick={() => setAccountOpen(value => !value)}>{data?.profile.company ? data.profile.company.slice(0, 2).toUpperCase() : "PL"}</button>{accountOpen && <div className="account-popover"><span className="small muted">{data?.profile.company || "Your private workspace"}</span><button onClick={() => { setAccountOpen(false); navigate("settings"); }}><Settings2 size={15}/>Workspace settings</button><button disabled={locking} onClick={lock}><LockKeyhole size={15}/>{locking ? "Locking…" : "Lock workspace"}</button></div>}</div></div></header>
    <div className="workspace-layout"><aside className="sidebar" aria-label="Permit views"><button className={`sidebar-main ${tab === "permits" && filters.age === "all" && !filters.onlyServiceArea ? "active" : ""}`} onClick={() => { navigate("permits"); changeFilters({ age: "all", onlyServiceArea: false, status: "all" }); }}><LayoutList size={17}/>All permits<ArrowRight size={16}/></button><span className="sidebar-label">WHEN IT HAPPENED</span><div className="sidebar-links">{AGE_ITEMS.slice(1).map(item => <button key={item.key} className={tab === "permits" && filters.age === item.key ? "active" : ""} onClick={() => { navigate("permits"); changeFilters({ age: item.key, onlyServiceArea: false }); }}><CalendarDays size={16}/><span>{item.label}</span>{stats && item.stat && <span className="sidebar-count">{stats[item.stat]}</span>}</button>)}</div><span className="sidebar-label">A LITTLE MORE FOCUS</span><div className="sidebar-links"><button className={filters.onlyServiceArea && tab === "permits" ? "active" : ""} onClick={() => { if (!data?.profile.counties.length && !data?.profile.trades.length) { navigate("settings"); notify("Choose your services and counties to personalize this view."); } else { navigate("permits"); changeFilters({ onlyServiceArea: true, age: "all" }); } }}><MapPin size={16}/><span>My service area</span></button><button className={filters.status === "open" && tab === "permits" ? "active" : ""} onClick={() => { navigate("permits"); changeFilters({ status: "open", age: "all", onlyServiceArea: false }); }}><Building2 size={16}/><span>Open permits</span></button></div><div className="sidebar-bottom"><div className="business-mini"><span className="business-avatar"><Building2 size={18}/></span><div><strong>{data?.profile.company || "Your business"}</strong><span>{data?.profile.trades.length ? `${data.profile.trades.length} services selected` : "Make your feed more relevant"}</span></div></div><button className="text-button" onClick={() => navigate("settings")}>{data?.profile.company ? "Edit preferences" : "Set up your services"}<ArrowRight size={14}/></button><div className="sidebar-footnote"><LockKeyhole size={12}/>Your private workspace</div></div></aside>
    <main className="workspace-main" id="main-content">{!data ? bootError ? <EmptyState icon={<Database size={27}/>} title="Let's reconnect" description={bootError} action={<button className="button button-secondary" onClick={boot}>Try again</button>}/> : <div className="panel-loading"><Spinner/><p>Preparing your workspace</p></div> : tab === "settings" ? <Settings data={data} theme={theme} setTheme={value => { if (value !== theme) toggleTheme(); }} onSave={saveProfile} notify={notify} onCopy={copy}/> : tab === "sources" ? <Sources notify={notify}/> : <>
      <div className="page-heading"><div><span className="eyebrow">FLORIDA / {tab === "saved" ? "YOUR SHORTLIST" : "PERMIT OPPORTUNITIES"}</span><h1>{tab === "saved" ? "Good projects. Kept close." : ageTitle}</h1><p>{tab === "saved" ? "Your saved leads, next steps and conversations in one place." : "Recent permits, organized around the work you do."}</p></div><button className="button button-primary export-button" disabled={!result?.total || loading || exporting} onClick={exportCsv}>{exporting ? <Spinner small/> : <Download size={16}/>}<span>Export CSV</span></button></div>
      {tab === "permits" && <div className="stats-strip"><div><span>Total permits</span><strong>{stats?.total ?? "—"}</strong><small>Across connected sources</small></div><div><span>Issued today</span><strong>{stats?.today ?? "—"}</strong><small>Fresh project activity</small></div><div><span>Commercial projects</span><strong>{stats?.commercial ?? "—"}</strong><small>Business permit records</small></div><div><span>Your saved leads</span><strong>{savedCount}</strong><small>A shortlist worth a look</small></div></div>}
      {!data.backendConnected && <div className="demo-note"><Database size={15}/><span>The permit feed is unavailable. Check Sources for the connection status.</span><button className="text-button" onClick={() => navigate("sources")}>Sources<ArrowRight size={13}/></button></div>}
      <div className="mobile-age-tabs" aria-label="Permit dates">{AGE_ITEMS.map(item => <button className={filters.age === item.key ? "active" : ""} key={item.key} onClick={() => changeFilters({ age: item.key })}>{item.key === "all" ? "All dates" : item.label}</button>)}</div>
      <section className="permits-panel" aria-label={tab === "saved" ? "Saved leads" : "Permit records"}><div className="panel-title-row"><div><h2>{tab === "saved" ? "Your leads" : "The latest opportunities"}</h2><span>{loading && !result ? "Loading…" : `${result?.total ?? 0} ${tab === "saved" ? "leads" : "permits"}`}</span></div><button className="icon-button" onClick={() => setVersion(value => value + 1)} disabled={loading} aria-label="Refresh permit records"><RefreshCw size={17} className={loading ? "rotating" : ""}/></button></div>
      {tab === "saved" && <div className="pipeline-tabs" aria-label="Lead status">{[{ value: "all", label: "All leads" }, { value: "saved", label: "Saved" }, { value: "contacted", label: "Contacted" }, { value: "won", label: "Won" }].map(item => <button className={filters.leadStatus === item.value ? "active" : ""} key={item.value} onClick={() => changeFilters({ leadStatus: item.value })}>{item.label}</button>)}</div>}
      <div className="filter-toolbar"><div className="search-field"><Search size={17}/><input ref={searchRef} aria-label="Search permits" value={search} onChange={event => { setSearch(event.target.value); setSelected(new Set()); }} placeholder="Search business, address or permit…"/>{search ? <button className="icon-button" onClick={() => setSearch("")} aria-label="Clear search"><X size={15}/></button> : <kbd>/</kbd>}</div><select aria-label="Filter by county" value={filters.county} onChange={event => changeFilters({ county: event.target.value })}><option value="all">All counties</option>{COUNTIES.map(county => <option value={county} key={county}>{county}</option>)}</select><select aria-label="Filter by trade" value={filters.trade} onChange={event => changeFilters({ trade: event.target.value })}><option value="all">All trades</option>{TRADES.map(trade => <option value={trade} key={trade}>{trade}</option>)}</select><button className="button button-secondary filter-button" onClick={() => { setFilterDraft(filters); setFilterOpen(true); }}><SlidersHorizontal size={16}/>Filters{(filters.status !== "all" || filters.minimumValue > 0 || !filters.hideDismissed) && <span className="filter-dot"/>}</button><div className="sort-field"><ArrowDownUp size={15}/><select aria-label="Sort permits" value={filters.sort} onChange={event => changeFilters({ sort: event.target.value })}><option value="newest">Newest first</option><option value="priority">Best fit first</option><option value="value">Highest value</option><option value="oldest">Oldest first</option></select></div></div>
      {hasFilters && <div className="active-filters"><span className="micro muted">Viewing</span>{filters.age !== "all" && <button onClick={() => changeFilters({ age: "all" })}>{AGE_ITEMS.find(item => item.key === filters.age)?.label}<X size={12}/></button>}{filters.county !== "all" && <button onClick={() => changeFilters({ county: "all" })}>{filters.county}<X size={12}/></button>}{filters.trade !== "all" && <button onClick={() => changeFilters({ trade: "all" })}>{filters.trade}<X size={12}/></button>}{filters.status !== "all" && <button onClick={() => changeFilters({ status: "all" })}>{filters.status === "open" ? "Open permits" : filters.status}<X size={12}/></button>}{filters.onlyServiceArea && <button onClick={() => changeFilters({ onlyServiceArea: false })}>My service area<X size={12}/></button>}{filters.minimumValue > 0 && <button onClick={() => changeFilters({ minimumValue: 0 })}>{money(filters.minimumValue, true)}+<X size={12}/></button>}{!filters.hideDismissed && <button onClick={() => changeFilters({ hideDismissed: true })}>Including dismissed<X size={12}/></button>}<button className="clear-filters" onClick={resetFilters}>Clear filters</button></div>}
      {selected.size > 0 && <div className="selection-bar"><span><Check size={15}/>{selected.size} selected</span><div><button className="text-button" onClick={bulkSave} disabled={saving}>{saving ? <Spinner small/> : <Bookmark size={14}/>}Save selected</button><button className="text-button" onClick={exportCsv} disabled={exporting}><Download size={14}/>Export selected</button><button className="icon-button" onClick={() => setSelected(new Set())} aria-label="Clear selection"><X size={15}/></button></div></div>}
      <div className={`results-content ${loading && result ? "is-loading" : ""}`} aria-busy={loading}>{loadError ? <EmptyState icon={<Database size={27}/>} title="The feed couldn't be loaded" description={loadError} action={<button className="button button-secondary" onClick={() => setVersion(value => value + 1)}>Try again</button>}/> : loading && !result ? <div className="panel-loading"><Spinner/><p>Finding permits</p></div> : rows.length === 0 ? <EmptyState icon={tab === "saved" ? <Bookmark size={28}/> : <Search size={28}/>} title={tab === "saved" && !savedCount ? "A shortlist starts with one project." : "No permits match this view."} description={tab === "saved" && !savedCount ? "Save a permit that looks relevant. Your leads and follow-up notes will stay together here." : "Try a broader date range, another county or fewer filters."} action={<button className="button button-secondary" onClick={() => { resetFilters(); if (tab === "saved" && !savedCount) navigate("permits"); }}>{tab === "saved" && !savedCount ? "Explore permits" : "Reset filters"}<ArrowRight size={15}/></button>}/> : <>
      <table className="permit-table"><thead><tr><th className="checkbox-col"><input type="checkbox" aria-label="Select all permits on this page" checked={allSelected} onChange={event => setSelected(event.target.checked ? new Set(rows.map(row => row.id)) : new Set())}/></th><th>Project</th><th>Location</th><th>Type & status</th><th>Permit date</th><th>Value</th><th><span className="priority-heading"><Sparkles size={13}/>Priority</span></th><th className="save-col"><span className="sr-only">Save lead</span></th></tr></thead><tbody>{rows.map(permit => { const status = data.leads[permit.id]?.status || "new", isSaved = ["saved", "contacted", "won"].includes(status); return <tr key={permit.id} className={selected.has(permit.id) ? "selected" : ""}><td className="checkbox-col"><input type="checkbox" aria-label={`Select ${permit.businessName || permit.title}`} checked={selected.has(permit.id)} onChange={event => setSelected(current => { const next = new Set(current); event.target.checked ? next.add(permit.id) : next.delete(permit.id); return next; })}/></td><td className="project-cell"><button className="project-button" onClick={() => setDetail(permit)}>{permit.businessName || permit.title}</button><span className="cell-secondary" title={permit.title}>{permit.title}</span></td><td><span>{permit.city || permit.county}</span><span className="cell-secondary">{permit.county} County</span></td><td><span className="trade-label">{permit.trade}</span><span className={`cell-secondary permit-status status-${permit.status.toLowerCase().replaceAll(" ", "-")}`}><span/>{permit.status}</span></td><td><span>{ageLabel(permitActivityDate(permit))}</span><span className="cell-secondary">{permitActivityDate(permit) ? `${permit.issuedAt ? "Issued" : "Applied"} ${new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "America/New_York" }).format(new Date(permitActivityDate(permit)!))}` : "—"}</span></td><td className="value-cell">{money(permit.value, true)}</td><td><button className={`priority-pill ${permit.priority >= 80 ? "strong" : ""}`} title={permit.priorityReasons.join(" · ")} onClick={() => setDetail(permit)}><span>{permit.priority}</span>{priorityLabel(permit.priority)}</button>{permit.assessment && <span className="cell-secondary">Jev assessed</span>}</td><td className="save-col"><button className={`icon-button bookmark-button ${isSaved ? "is-saved" : ""}`} aria-label={isSaved ? `Manage saved lead ${permit.businessName}` : `Save ${permit.businessName || permit.title}`} onClick={() => bookmark(permit)}><Bookmark size={18} fill={isSaved ? "currentColor" : "none"}/></button></td></tr>; })}</tbody></table>
      <div className="mobile-permit-list">{rows.map(permit => { const status = data.leads[permit.id]?.status || "new", isSaved = ["saved", "contacted", "won"].includes(status); return <article className={`mobile-permit ${selected.has(permit.id) ? "selected" : ""}`} key={permit.id}><div className="mobile-permit-top"><input type="checkbox" aria-label={`Select ${permit.businessName || permit.title}`} checked={selected.has(permit.id)} onChange={event => setSelected(current => { const next = new Set(current); event.target.checked ? next.add(permit.id) : next.delete(permit.id); return next; })}/><button className="project-button" onClick={() => setDetail(permit)}>{permit.businessName || permit.title}</button><button className="icon-button" aria-label={isSaved ? "Manage saved lead" : "Save lead"} onClick={() => bookmark(permit)}><Bookmark size={18} fill={isSaved ? "currentColor" : "none"}/></button></div><button className="mobile-project-detail" onClick={() => setDetail(permit)}><p>{permit.title}</p><span className="mobile-location"><MapPin size={12}/>{permit.city}, {permit.county}</span></button><div className="mobile-permit-meta"><span className="badge">{permit.trade}</span><span className="micro muted">{permit.status}</span><span className="priority-mobile">{permit.priority} · {priorityLabel(permit.priority)}</span></div><div className="mobile-permit-bottom"><span>{!permit.issuedAt && permit.appliedAt ? "Applied · " : ""}{ageLabel(permitActivityDate(permit))}</span><strong>{money(permit.value, true)}</strong></div></article>; })}</div></> }</div>
      {!loadError && <footer className="table-footer"><span className="small muted">{result?.total ? `${(page - 1) * pageSize + 1}–${Math.min(page * pageSize, result.total)} of ${result.total} ${tab === "saved" ? "leads" : "permits"}` : "0 permits"}</span><div><label className="page-size-label"><span>Rows</span><select aria-label="Rows per page" value={pageSize} onChange={event => { setPageSize(Number(event.target.value)); setPage(1); setSelected(new Set()); }}><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option></select></label><span className="page-count">{page} / {totalPages}</span><button className="icon-button" disabled={page <= 1 || loading} aria-label="Previous page" onClick={() => { setPage(value => value - 1); setSelected(new Set()); }}><ChevronLeft size={18}/></button><button className="icon-button" disabled={page >= totalPages || loading} aria-label="Next page" onClick={() => { setPage(value => value + 1); setSelected(new Set()); }}><ChevronRight size={18}/></button></div></footer>}
      </section><div className="workspace-footnote"><span><LockKeyhole size={12}/>Private workspace</span><span>{result?.mode === "live" ? `Feed updated ${permitDate(result.updatedAt)}` : "Florida permit records"}</span></div>
    </>}</main></div>
    <PermitDetail permit={detail} lead={detail ? data?.leads[detail.id] || newLead : newLead} onClose={() => setDetail(null)} onUpdate={(id, update) => updateLeads([{ id, ...update }], update.notes !== undefined ? "Your note is saved." : "Lead status updated.")} onCopy={copy} onAssess={assess} jevConnected={!!data?.jevConnected} jevEnabled={!!data?.profile.jevEnabled} onSettings={() => navigate("settings")}/>
    <Dialog open={filterOpen} onClose={() => setFilterOpen(false)} title="Refine your permits"><div className="modal-body"><h2>A little more focus.</h2><label className="field-label" htmlFor="filter-permit-status">Permit status</label><select id="filter-permit-status" value={filterDraft.status} onChange={event => setFilterDraft({ ...filterDraft, status: event.target.value })}><option value="all">All statuses</option><option value="open">Open: issued or in review</option><option value="Issued">Issued</option><option value="In review">In review</option><option value="Closed">Closed</option><option value="Unknown">Unknown</option></select><label className="field-label" htmlFor="filter-property-type">Property type</label><select id="filter-property-type" value={filterDraft.propertyType} onChange={event => setFilterDraft({ ...filterDraft, propertyType: event.target.value })}><option value="all">Commercial & residential</option><option value="Commercial">Commercial</option><option value="Residential">Residential</option><option value="Unknown">Unknown</option></select><label className="field-label" htmlFor="filter-project-value">Minimum project value</label><div className="currency-input"><span>$</span><input id="filter-project-value" type="number" min={0} value={filterDraft.minimumValue || ""} placeholder="No minimum" onChange={event => setFilterDraft({ ...filterDraft, minimumValue: Number(event.target.value) || 0 })}/></div><label className="check-line"><input type="checkbox" checked={!filterDraft.hideDismissed} onChange={event => setFilterDraft({ ...filterDraft, hideDismissed: !event.target.checked })}/>Include dismissed leads</label><div className="modal-actions"><button className="button button-secondary" onClick={() => { setFilterDraft({ ...filterDraft, status: "all", propertyType: "all", minimumValue: 0, hideDismissed: true }); }}>Reset</button><button className="button button-primary" onClick={() => { changeFilters(filterDraft); setFilterOpen(false); }}>Apply filters<ArrowRight size={16}/></button></div></div></Dialog><Toast toast={toast} onClose={closeToast}/>
  </div>;
}
