"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, Bookmark, Check, Copy, FileText, MapPin, Phone, Sparkles } from "lucide-react";
import type { LeadState, LeadStatus, Permit } from "../lib/types";
import { ageLabel, money, permitDate, priorityLabel } from "../lib/permit-utils";
import { Dialog, Spinner } from "./ui";

export default function PermitDetail({ permit, lead, onClose, onUpdate, onCopy, onAssess, jevConnected, jevEnabled, onSettings }: {
  permit: Permit | null; lead: LeadState; onClose: () => void; onUpdate: (id: string, update: Partial<LeadState>) => Promise<void>; onCopy: (text: string, label: string) => void; onAssess: (ids: string[]) => Promise<void>; jevConnected: boolean; jevEnabled: boolean; onSettings: () => void;
}) {
  const [notes, setNotes] = useState(""), [busy, setBusy] = useState(false), [assessing, setAssessing] = useState(false), [noteSaved, setNoteSaved] = useState(false);
  useEffect(() => { setNotes(lead.notes); setNoteSaved(false); }, [permit?.id]);
  async function update(value: Partial<LeadState>) { if (!permit) return; setBusy(true); try { await onUpdate(permit.id, value); if (value.notes !== undefined) setNoteSaved(true); } catch {} finally { setBusy(false); } }
  return <Dialog open={!!permit} onClose={onClose} title="Permit details" drawer>{permit && <>
    <div className="detail-intro"><div className="detail-eyebrow"><span>{permit.permitNumber}</span></div><h2>{permit.title}</h2><p className="detail-business">{permit.businessName || "Business not listed"}</p><div className="detail-location"><MapPin size={16}/><span>{permit.address}<br/>{permit.city}{permit.city && permit.county ? ", " : ""}{permit.county} County, FL</span></div><div className="detail-tags"><span className="badge">{permit.trade}</span><span className="badge">{permit.propertyType}</span><span className="badge">{permit.status}</span></div></div>
    <div className="detail-section"><div className="section-title"><h3>At a glance</h3><span className="muted small">{ageLabel(permit.issuedAt)}</span></div><dl className="detail-facts"><div><dt>Project value</dt><dd>{money(permit.value)}</dd></div><div><dt>Issued</dt><dd>{permitDate(permit.issuedAt)}</dd></div><div><dt>Applied</dt><dd>{permitDate(permit.appliedAt)}</dd></div><div><dt>Source status</dt><dd>{permit.rawStatus}</dd></div></dl></div>
    <div className="detail-section"><h3>Scope of work</h3><p className="detail-description">{permit.description}</p></div>
    <div className="detail-section"><div className="section-title"><h3><Sparkles size={16}/> Priority</h3><span className={`badge ${permit.priority >= 80 ? "badge-solid" : ""}`}>{priorityLabel(permit.priority)}</span></div><div className="priority-score"><strong>{permit.priority}<span>/100</span></strong><span className="muted small">{permit.assessment ? "Assessed with Jev" : "Service profile preview"}</span></div><div className="priority-meter" aria-label={`Priority index ${permit.priority} out of 100`}><span style={{ width: `${permit.priority}%` }}/></div><ul className="priority-reasons">{permit.priorityReasons.map(reason => <li key={reason}><Check size={14}/>{reason}</li>)}</ul><p className="micro muted">Priority reflects service fit and project signals.</p>{permit.assessment?.confidence !== null && permit.assessment?.confidence !== undefined && <p className="micro muted">Assessment confidence: {Math.round(permit.assessment.confidence * 100)}%</p>}
      <button className="button button-secondary button-small" disabled={assessing} onClick={async () => { if (!jevConnected || !jevEnabled) { onClose(); onSettings(); return; } setAssessing(true); try { await onAssess([permit.id]); } catch {} finally { setAssessing(false); } }}>{assessing ? <Spinner small/> : <Sparkles size={15}/>} {jevConnected && jevEnabled ? "Assess with Jev" : "Set up Jev"}</button></div>
    <div className="detail-section"><div className="section-title"><h3>Listed contact</h3>{permit.contactRole !== "Unknown" && <span className="badge badge-subtle">{permit.contactRole}</span>}</div>{permit.contactName || permit.phone || permit.email ? <div className="contact-block"><p>{permit.contactName || "Name not listed"}</p>{permit.phone && <div className="contact-line"><Phone size={15}/><span>{permit.phone}</span><button className="icon-button" onClick={() => onCopy(permit.phone!, "Phone number")} aria-label="Copy phone number"><Copy size={15}/></button></div>}{permit.email && <div className="contact-line"><span>{permit.email}</span><button className="icon-button" onClick={() => onCopy(permit.email!, "Email address")} aria-label="Copy email address"><Copy size={15}/></button></div>}</div> : <p className="muted small">This source hasn't provided contact details.</p>}</div>
    <div className="detail-section"><h3>Your follow-up</h3><label className="field-label" htmlFor="lead-status">Lead status</label><select id="lead-status" value={lead.status} disabled={busy} onChange={event => update({ status: event.target.value as LeadStatus })}><option value="new">Not saved</option><option value="saved">Saved</option><option value="contacted">Contacted</option><option value="won">Won</option><option value="dismissed">Dismissed</option></select><label className="field-label" htmlFor="lead-notes">Private notes</label><textarea id="lead-notes" rows={4} maxLength={10000} value={notes} onChange={event => { setNotes(event.target.value); setNoteSaved(false); }} placeholder="Add a contact, next step or reminder…"/><div className="notes-actions"><span className="micro muted">Only visible in your workspace.</span><button className="button button-secondary button-small" disabled={busy || notes === lead.notes} onClick={() => update({ notes })}>{busy ? <Spinner small/> : noteSaved ? <Check size={14}/> : <FileText size={14}/>} {noteSaved ? "Saved" : "Save note"}</button></div></div>
    <div className="detail-footer"><button className="button button-primary" disabled={busy} onClick={() => update({ status: lead.status === "new" || lead.status === "dismissed" ? "saved" : lead.status === "saved" ? "new" : lead.status })}><Bookmark size={16} fill={!["new", "dismissed"].includes(lead.status) ? "currentColor" : "none"}/>{["new", "dismissed"].includes(lead.status) ? "Save lead" : lead.status === "saved" ? "Remove from saved" : "Lead in your pipeline"}</button>{permit.sourceUrl && <a className="button button-secondary" href={permit.sourceUrl} target="_blank" rel="noopener noreferrer">View source <ArrowUpRight size={16}/></a>}</div>
  </>}</Dialog>;
}
