"use client";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowUpRight, Check, CircleHelp, Copy, KeyRound, LockKeyhole, Monitor, Moon, Search, Sparkles, Sun, Workflow } from "lucide-react";
import { api } from "../lib/client";
import { COUNTIES, TRADES, type Profile, type WorkspaceData } from "../lib/types";
import { Dialog, Spinner } from "./ui";

export default function Settings({ data, theme, setTheme, onSave, notify, onCopy }: { data: WorkspaceData; theme: string; setTheme: (theme: string) => void; onSave: (profile: Profile) => Promise<void>; notify: (message: string, error?: boolean) => void; onCopy: (text: string, label: string) => void }) {
  const [draft, setDraft] = useState<Profile>(data.profile), [countySearch, setCountySearch] = useState(""), [saving, setSaving] = useState(false), [connection, setConnection] = useState<"jev" | "feed" | null>(null), [passwordOpen, setPasswordOpen] = useState(false);
  const [currentPassword, setCurrentPassword] = useState(""), [newPassword, setNewPassword] = useState(""), [confirm, setConfirm] = useState(""), [passwordBusy, setPasswordBusy] = useState(false), [passwordError, setPasswordError] = useState("");
  useEffect(() => { setDraft(data.profile); }, [data.profile]);
  const dirty = JSON.stringify(draft) !== JSON.stringify(data.profile);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); try { await onSave(draft); } catch {} finally { setSaving(false); } }
  async function changePassword(event: FormEvent) {
    event.preventDefault(); setPasswordError("");
    if (newPassword !== confirm) { setPasswordError("Your new passwords don't match."); return; }
    if (newPassword.length < 10) { setPasswordError("Use at least 10 characters."); return; }
    setPasswordBusy(true);
    try { await api("/api/auth/password", { method: "POST", body: JSON.stringify({ currentPassword, password: newPassword }) }); setPasswordOpen(false); setCurrentPassword(""); setNewPassword(""); setConfirm(""); notify("Password updated. Other sessions are now locked."); }
    catch (e) { setPasswordError(e instanceof Error ? e.message : "Please try again."); }
    finally { setPasswordBusy(false); }
  }
  return <div className="settings-page"><div className="page-heading"><div><span className="eyebrow">YOUR WORKSPACE</span><h1>Make it work for you.</h1><p>Your services, your area, your way of working.</p></div></div><form onSubmit={save}>
    <section className="settings-card"><div className="settings-section-heading"><span className="section-number">01</span><div><h2>Your business</h2><p>Help us bring the relevant projects to the top.</p></div></div><div className="settings-fields"><label className="field-label" htmlFor="company-name">Business name</label><input id="company-name" maxLength={120} placeholder="Your company name" value={draft.company} onChange={e => setDraft({ ...draft, company: e.target.value })}/><span className="field-label">Your services</span><div className="choice-chips">{TRADES.map(trade => <button type="button" key={trade} className={`choice-chip ${draft.trades.includes(trade) ? "is-selected" : ""}`} aria-pressed={draft.trades.includes(trade)} onClick={() => setDraft({ ...draft, trades: draft.trades.includes(trade) ? draft.trades.filter(t => t !== trade) : [...draft.trades, trade] })}>{draft.trades.includes(trade) && <Check size={13}/>} {trade}</button>)}</div><p className="micro muted">Leave services empty to review all trades.</p><div className="settings-two-fields"><div><label className="field-label" htmlFor="minimum-value">Preferred minimum project value</label><div className="currency-input"><span>$</span><input id="minimum-value" type="number" min={0} max={1e10} value={draft.minimumValue || ""} onChange={e => setDraft({ ...draft, minimumValue: Number(e.target.value) || 0 })} placeholder="No minimum"/></div></div><label className="switch-row compact"><span><strong>Commercial projects</strong><span className="micro muted">Default to business permits</span></span><input className="switch" type="checkbox" checked={draft.commercialOnly} onChange={e => setDraft({ ...draft, commercialOnly: e.target.checked })}/></label></div></div></section>
    <section className="settings-card"><div className="settings-section-heading"><span className="section-number">02</span><div><h2>Your service area</h2><p>Select the counties where you want to find work.</p></div></div><div className="settings-fields"><div className="county-selection-heading"><span>{draft.counties.length ? `${draft.counties.length} counties selected` : "All Florida counties"}</span><button type="button" className="text-button" onClick={() => setDraft({ ...draft, counties: [] })}>Clear selection</button></div><div className="search-field"><Search size={16}/><input aria-label="Search Florida counties" value={countySearch} onChange={e => setCountySearch(e.target.value)} placeholder="Find a county…"/></div><div className="county-grid">{COUNTIES.filter(county => county.toLowerCase().includes(countySearch.toLowerCase())).map(county => <label key={county} className="county-choice"><input type="checkbox" checked={draft.counties.includes(county)} onChange={e => setDraft({ ...draft, counties: e.target.checked ? [...draft.counties, county] : draft.counties.filter(c => c !== county) })}/><span>{county}</span></label>)}{!COUNTIES.some(county => county.toLowerCase().includes(countySearch.toLowerCase())) && <p className="muted small">No counties match that search.</p>}</div><p className="micro muted">County filters include permits from connected city and county sources.</p></div></section>
    <section className="settings-card"><div className="settings-section-heading"><span className="section-number">03</span><div><h2>Priority with Jev</h2><p>Structured assessments that help you decide what to review first.</p></div></div><div className="settings-fields"><div className="connection-row"><div className="connection-icon"><Sparkles size={21}/></div><div><strong>Jev decision engine</strong><p className="small muted">Service fit and scope classification</p></div><span className={`badge ${data.jevConnected ? "badge-solid" : ""}`}>{data.jevConnected ? "Connected" : "Not connected"}</span></div><label className="switch-row"><span><strong>Use Jev assessments in priority</strong><span className="small muted">New assessments are run when you choose “Assess with Jev”.</span></span><input className="switch" type="checkbox" disabled={!data.jevConnected} checked={draft.jevEnabled && data.jevConnected} onChange={e => setDraft({ ...draft, jevEnabled: e.target.checked })}/></label><div className="settings-helper"><CircleHelp size={15}/><p>Priority is a service-fit index. It does not measure your chance of winning a client.</p></div><button type="button" className="button button-secondary button-small" onClick={() => setConnection("jev")}>{data.jevConnected ? "Connection details" : "Set up connection"}<ArrowUpRight size={15}/></button></div></section>
    <div className="settings-savebar"><span className="small muted">{dirty ? "You have unsaved changes." : "Your business profile is saved."}</span><div><button type="button" className="button button-secondary" disabled={!dirty || saving} onClick={() => setDraft(data.profile)}>Discard</button><button type="submit" className="button button-primary" disabled={!dirty || saving}>{saving ? <Spinner small/> : <Check size={16}/>}Save preferences</button></div></div></form>
    <div className="settings-bottom-grid"><section className="settings-card"><div className="section-title"><h2>Appearance</h2><Monitor size={18}/></div><p className="small muted">Choose a workspace that feels right.</p><div className="theme-choices"><button className={`theme-choice ${theme === "light" ? "is-selected" : ""}`} aria-pressed={theme === "light"} onClick={() => setTheme("light")}><span className="theme-swatch swatch-light"><span/><span/><span/></span><span><Sun size={15}/>Light{theme === "light" && <Check size={14}/>}</span></button><button className={`theme-choice ${theme === "dark" ? "is-selected" : ""}`} aria-pressed={theme === "dark"} onClick={() => setTheme("dark")}><span className="theme-swatch swatch-dark"><span/><span/><span/></span><span><Moon size={15}/>Pure black{theme === "dark" && <Check size={14}/>}</span></button></div></section><section className="settings-card"><div className="section-title"><h2>Access & connection</h2><LockKeyhole size={18}/></div><div className="simple-setting-row"><span><strong>Password protection</strong><span className="micro muted">Required to open your workspace</span></span><button className="text-button" onClick={() => { setPasswordError(""); setPasswordOpen(true); }}>Change</button></div><div className="simple-setting-row"><span><strong>Permit feed</strong><span className="micro muted">{data.backendConnected ? "Your collector API is configured" : "Sample data until your collector is connected"}</span></span><button className="text-button" onClick={() => setConnection("feed")}>Details</button></div></section></div>
    <Dialog open={connection !== null} onClose={() => setConnection(null)} title={connection === "jev" ? "Connect Jev" : "Connect your permit feed"}><div className="modal-body"><div className="modal-symbol">{connection === "jev" ? <Sparkles size={25}/> : <Workflow size={25}/>}</div><h2>{connection === "jev" ? "A smarter priority layer." : "Bring your permits into view."}</h2><p className="muted">{connection === "jev" ? "The dashboard integration is ready. Configure your AI/ML API key on the server to enable live assessments." : "Your OpenMausBot collector supplies the permit data. Connect its backend API to replace the sample records."}</p><div className="connection-key"><code>{connection === "jev" ? "AIMLAPI_KEY" : "PERMIT_API_URL"}</code><button className="icon-button" aria-label="Copy configuration key name" onClick={() => onCopy(connection === "jev" ? "AIMLAPI_KEY" : "PERMIT_API_URL", "Configuration key")}><Copy size={16}/></button></div><p className="small muted">{connection === "jev" ? "Keep the key in the hosted server environment. It never belongs in browser code." : "Set the HTTPS backend origin in the hosted server environment. Add PERMIT_API_TOKEN as a server secret if your API requires it."}</p>{connection === "jev" && <a className="button button-secondary" href="https://aimlapi.com/app/keys" target="_blank" rel="noopener noreferrer">Open AI/ML API console <ArrowUpRight size={16}/></a>}<button className="button button-primary" onClick={() => setConnection(null)}>Got it</button></div></Dialog>
    <Dialog open={passwordOpen} onClose={() => { if (!passwordBusy) { setPasswordOpen(false); setCurrentPassword(""); setNewPassword(""); setConfirm(""); } }} title="Change workspace password"><form className="modal-body" onSubmit={changePassword}><div className="modal-symbol"><KeyRound size={24}/></div><h2>Update your password.</h2><label className="field-label" htmlFor="current-password">Current password</label><input id="current-password" type="password" autoComplete="current-password" required value={currentPassword} onChange={e => setCurrentPassword(e.target.value)}/><label className="field-label" htmlFor="new-password">New password</label><input id="new-password" type="password" autoComplete="new-password" minLength={10} maxLength={200} required placeholder="At least 10 characters" value={newPassword} onChange={e => setNewPassword(e.target.value)}/><label className="field-label" htmlFor="new-password-confirm">Confirm new password</label><input id="new-password-confirm" type="password" autoComplete="new-password" required minLength={10} maxLength={200} value={confirm} onChange={e => setConfirm(e.target.value)}/>{passwordError && <p className="form-error" role="alert">{passwordError}</p>}<button className="button button-primary button-full" disabled={passwordBusy}>{passwordBusy ? <Spinner small/> : "Update password"}</button></form></Dialog>
  </div>;
}
