"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, Database, RefreshCw, Search } from "lucide-react";
import type { Source } from "../lib/types";
import { api } from "../lib/client";
import { permitDate } from "../lib/permit-utils";
import { EmptyState, Spinner } from "./ui";
export default function Sources({ notify }: { notify: (message: string, error?: boolean) => void }) {
  const [sources, setSources] = useState<Source[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [search, setSearch] = useState("");
  async function load() { setLoading(true); setError(""); try { const data = await api<{ sources: Source[] }>("/api/sources"); setSources(data.sources); } catch (e) { setError(e instanceof Error ? e.message : "Please try again."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const filtered = sources.filter(source => `${source.name} ${source.county}`.toLowerCase().includes(search.toLowerCase())), connected = sources.filter(s => s.status !== "not-connected").length;
  return <section className="sources-page"><div className="page-heading"><div><span className="eyebrow">BEHIND THE PERMITS</span><h1>A clear view of your sources.</h1><p>Know where each record comes from and how fresh it is.</p></div><button className="button button-secondary" onClick={load} disabled={loading}>{loading ? <Spinner small/> : <RefreshCw size={16}/>}Refresh</button></div><div className="stats-strip source-stats"><div><span>Sources listed</span><strong>{loading ? "—" : sources.length}</strong></div><div><span>Connected</span><strong>{loading ? "—" : connected}</strong></div><div><span>Healthy feeds</span><strong>{loading ? "—" : sources.filter(s => s.status === "healthy").length}</strong></div></div><div className="sources-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Search permit sources" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search a city or county…"/></div><span className="small muted">Florida sources</span></div>{error ? <EmptyState icon={<Database size={27}/>} title="Source health is unavailable" description={error} action={<button className="button button-secondary" onClick={load}>Try again</button>}/> : loading ? <div className="panel-loading"><Spinner/><span>Checking sources</span></div> : !filtered.length ? <EmptyState icon={<Search size={25}/>} title="No sources found" description="Try another county or city name." action={<button className="text-button" onClick={() => setSearch("")}>Clear search</button>}/> : <div className="source-list">{filtered.map(source => <article className="source-card" key={source.id}><div className="source-card-heading"><span className="source-icon"><Database size={18}/></span><div><h2>{source.name}</h2><span className="small muted">{source.county} County</span></div><span className={`badge ${source.status === "healthy" ? "badge-solid" : ""}`}>{source.status === "not-connected" ? "Not connected" : source.status === "healthy" ? "Healthy" : source.status === "stale" ? "Stale" : "Needs attention"}</span></div><p className="source-note">{source.note}</p><div className="source-card-bottom"><span className="micro muted">Last successful check: {source.lastSuccessAt ? permitDate(source.lastSuccessAt) : "Not yet"}</span>{source.url && <a href={source.url} className="text-button" target="_blank" rel="noopener noreferrer">Source portal <ArrowUpRight size={14}/></a>}</div></article>)}</div>}<p className="sources-footnote"><Database size={15}/>Coverage expands as your collector connects more issuing authorities.</p></section>;
}
